### ISSUE TITLE
Best embedding LLM model

### ISSUE THREAD

**Issue by lbarasc** [TufayelLUS/RAG-Scraper-AI-GUI#2]
Hi, thank you for your software.
Can you advice some fast and relevant embedding LLM models ? (especially for multilingual text)

**Comment by TufayelLUS** [comment]
Hi, it's my pleasure. You may explore https://ollama.com/library for different libraries and play around with them. I found llama3.2 faster so far but for multilingual support, I'm not sure about its performance.

**Comment by TufayelLUS** [comment]
> Hi, thank you for your software. Can you advice some fast and relevant embedding LLM models ? (especially for multilingual text)

Hi, it's my pleasure. I initially thought that you were asking for the model as a suggestion but then noticed that you mentioned embeddings model. I found all-minilm okay so far but you may try other embedding models like [nomic-embed-text](https://ollama.com/library/nomic-embed-text) but I'm not sure about their multilingual support. You might want to explore the library on https://ollama.com/library
